modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/EnvyWare/BetterPokeBroadcaster/issues"

[[mods]]
modId="betterpokebroadcaster"
version="2.1.0"
displayName="BetterPokeBroadcaster"
displayURL="https://github.com/EnvyWare"
credits="https://github.com/EnvyWare"
authors="https://github.com/EnvyWare"
description='''
Adds TRACKING
'''

[[dependencies.betterpokebroadcaster]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.betterpokebroadcaster]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"