modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/EnvyWare/BetterPokeBroadcaster/issues"

[[mods]]
modId="betterpokebroadcaster"
version="1.3.0"
displayName="BetterPokeBroadcaster"
displayURL="https://github.com/EnvyWare"
credits="https://github.com/EnvyWare"
authors="https://github.com/EnvyWare"
description='''
Adds TRACKING
'''

[[dependencies.betterpokebroadcaster]]
modId="forge"
mandatory=true
versionRange="[47.1.28,)"
ordering="NONE"
side="BOTH"

[[dependencies.betterpokebroadcaster]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"